name: Testrunner - FE

on:
  push:
    branches: [ master, 'frontend-**', 'frontend_**' ]
    paths-ignore: [ 'docs/**', 'backend/**', 'deliverables/**', '.github/**' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ 'docs/**', 'backend/**', 'deliverables/**', '.github/**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd frontend && npm install
    - run: cd frontend && npm run build --if-present
    - run: cd frontend && npm test
      env:
        CI: true
